version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:

      SECRET_KEY: "your_secret_key"
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://username:password@db_host:db_port/db_name"
      
    volumes:
      - .:/app

    networks:
      app-network:
        ipv4_address: 10.1.0.5

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24
