version: '3.8'

services:
  moringa_attendance:
    build: .
    container_name: moringa_attendance
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      app-network:
        ipv4_address: 10.1.0.5

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24
